# Generated by Django 4.2.30 on 2026-04-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movement_performed_by_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to='core.location'),
        ),
    ]
